[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true

remappings = [
    "@onchain-id/solidity/=lib/solidity/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
]

[dependencies]
forge-std = "1.11.0"
"@oasisprotocol-sapphire-contracts" = "0.2.14"
"@oasisprotocol-sapphire-foundry" = "0.1.1"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
